<?php 
	/**
	 * @instantiate Helper Class
	 */
	$rocket = $this->helper('Primeview\Rocket\Helper\Data'); 
?>
<footer class="footer">
	<div class="top">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h3>Company</h3>

				</div>
				<div class="col-md-3">
					<h3>Support</h3>

				</div>
				<div class="col-md-3">
					<h3>Industry</h3>

				</div>
				<div class="col-md-3">
					<?php echo $rocket->getLogo($this); ?>
					<h4>1-800-834-2563</h4>

				</div>
			</div>
		</div>
	</div> 
	<div class="bot">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					
				</div>
				<div class="col-md-4">
					
				</div>
				<div class="col-md-4">
					<p>&copy; Copyright <?php echo date('Y'); ?> JPC . All rights reserved</p>
				</div>
			</div>
		</div>
	</div>
</footer> 
