<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<a href="#"><i aria-hidden="true" class="fa fa-search"></i></a>

<div class="search-overlay">
	<a id="close-search"><i class="fa fa-times" aria-hidden="true"></i></a>
	<div class="block block-search">
		<div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
		<div class="block block-content">
			<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
				<div class="field search">
					<label class="label" for="search" data-role="minisearch-label">
						<span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
					</label>
					<div class="control">
						<input id="search"
							   data-mage-init='{"quickSearch":{
									"formSelector":"#search_mini_form",
									"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
									"destinationSelector":"#search_autocomplete"}
							   }'
							   type="text"
							   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
							   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
							   placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
							   class="input-text"
							   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
							   role="combobox"
							   aria-haspopup="false"
							   aria-autocomplete="both"
							   autocomplete="off"/>
						<div id="search_autocomplete" class="search-autocomplete"></div>
						<?php echo $block->getChildHtml() ?>
					</div>
				</div>
				<div class="actions">
					<button type="submit"
							title="<?php echo $block->escapeHtml(__('Search')) ?>"
							class="action search">
						<span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$j = jQuery.noConflict();
	$j(function(){
		$j('ul.social li.search a').click(function(e){
			//console.log(e);
			$j('.search-overlay').toggleClass('show');
			$j('body').toggleClass('no-scroll');
		});
	})
</script>